<a href="https://colab.research.google.com/github/SeohaLim0501/AICE-Study/blob/main/Chapter_03_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EA%B5%AC%EC%A1%B0_%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 01: 데이터프레임 확인하기

## Clean_Dataset.csv 가져오기

In [20]:
import numpy as np
import pandas as pd

In [21]:
!wget -O flight.zip "https://www.kaggle.com/api/v1/datasets/download/shubhambathwal/flight-price-prediction"
!unzip -o flight.zip
!rm -f flight.zip
!rm -f business.csv economy.csv

--2026-10-25 06:30:54--  https://www.kaggle.com/api/v1/datasets/download/shubhambathwal/flight-price-prediction
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com:443/kaggle-data-sets/1957837/3228623/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20261025%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20261025T054213Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=5fb97101f3ee773cdb2340b04b8961c9d8c383d81dd0ebd5e47f0e01c82252ccf5b203b8241aea29d3348874efb396d4ec607ac14374bc5792d0b38b30812c2ce929754538c6c3429b8fe3a0fc17289c6f78add80996bf16e2092c38ed81565728db00b58c409a3248daef1736bf17eb038b1aa5adc6e2a78342dfeb656ad3b0ced45e91b33de7ecce1255c33c50334f81bdc31602f36d9fb704c0057a9f1a241f049d8a2e1fb0fe111c71902caee046d3c65718b8c5a17bfce0a4dd7a0d353dc26b8899bb6f5dabae7c347658273024a5157bae9089528f50548845dffa0fd3212291b2cfac3fb84367bd91a78842917433ae39920ed79ca6997b587abb3d45 [following]
--2026-10-25 06:30:54--  https://storage.googleapis.com/kaggle-data-sets/1957837/3228623/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20261025%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20261025T054213Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=5fb97101f3ee773cdb2340b04b8961c9d8c383d81dd0ebd5e47f0e01c82252ccf5b203b8241aea29d3348874efb396d4ec607ac14374bc5792d0b38b30812c2ce929754538c6c3429b8fe3a0fc17289c6f78add80996bf16e2092c38ed81565728db00b58c409a3248daef1736bf17eb038b1aa5adc6e2a78342dfeb656ad3b0ced45e91b33de7ecce1255c33c50334f81bdc31602f36d9fb704c0057a9f1a241f049d8a2e1fb0fe111c71902caee046d3c65718b8c5a17bfce0a4dd7a0d353dc26b8899bb6f5dabae7c347658273024a5157bae9089528f50548845dffa0fd3212291b2cfac3fb84367bd91a78842917433ae39920ed79ca6997b587abb3d45
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.107.207, 74.125.139.207, 173.194.210.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.107.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4360218 (4.2M) [application/zip]
Saving to: ‘flight.zip’

flight.zip          100%[===================>]   4.16M  --.-KB/s    in 0.03s

2026-10-25 06:30:54 (124 MB/s) - ‘flight.zip’ saved [4360218/4360218]

Archive:  flight.zip
  inflating: Clean_Dataset.csv
  inflating: business.csv
  inflating: economy.csv

In [22]:
flight = pd.read_csv('./Clean_Dataset.csv', encoding = "cp949")
flight

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

## head(), tail()

In [23]:
flight.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [24]:
flight.tail()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [25]:
flight.tail(n = 10)

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300143,300143,Air_India,AI-440,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.42,49,51345
300144,300144,Air_India,AI-539,Chennai,Evening,one,Morning,Hyderabad,Business,18.92,49,51345
300145,300145,Air_India,AI-430,Chennai,Morning,one,Morning,Hyderabad,Business,23.08,49,51345
300146,300146,Air_India,AI-440,Chennai,Early_Morning,one,Morning,Hyderabad,Business,26.83,49,51345
300147,300147,Air_India,AI-569,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.25,49,68739
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

## DataFrame 정보 확인

In [26]:
flight.shape # 튜플로 반환, (row, col)

(300153, 12)

In [27]:
flight.columns

Index(['Unnamed: 0', 'airline', 'flight', 'source_city', 'departure_time',
       'stops', 'arrival_time', 'destination_city', 'class', 'duration',
       'days_left', 'price'],
      dtype='object')

In [28]:
flight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [29]:
flight.dtypes # 칼럼 별 데이터프레임이 가지는 데이터 형태의 종류를 표시

Unnamed: 0            int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
dtype: object

In [30]:
'''
flight['airline']             # 하나의 열 선택 → Series
flight[['airline', 'price']]  # 여러 열 선택 → DataFrame
flight[flight['price'] > 5000] # 조건에 맞는 행 선택 → DataFrame
'''

flight['source_city'].value_counts()

source_city
Delhi        61343
Mumbai       60896
Bangalore    52061
Kolkata      46347
Hyderabad    40806
Chennai      38700
Name: count, dtype: int64

### describe()

In [31]:
# column별 요약 통계량 표시할 때는 describe() 사용
# float, int 처럼 숫자형 데이터의 통계치를 확인

flight.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [32]:
# 범주형 데이터의 정보까지 확인하기 위해서는 include = 'all' 사용

flight.describe(include = 'all')

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
count,300153.000000,300153,300153,300153,300153,300153,300153,300153,300153,300153.000000,300153.000000,300153.000000
unique,NaN,6,1561,6,6,3,6,6,2,NaN,NaN,NaN
top,NaN,Vistara,UK-706,Delhi,Morning,one,Night,Mumbai,Economy,NaN,NaN,NaN
freq,NaN,127859,3235,61343,71146,250863,91538,59097,206666,NaN,NaN,NaN
mean,150076.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.221021,26.004751,20889.660523
std,86646.852011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.191997,13.561004,22697.767366
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.830000,1.000000,1105.000000
25%,75038.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.830000,15.000000,4783.000000
50%,150076.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.250000,26.000000,7425.000000
75%,225114.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.170000,38.000000,42521.000000
max,300152.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.830000,49.000000,123071.000000